### ISSUE TITLE
Tests not refreshed when first changed

### ISSUE THREAD

**Issue by optilude** [thereactivestack/kickstart-meteor-react#26]
Tests seem to be cached somehow. Tested with server integration tests, but may occur elsewhere too.

1. Start up meteor.  `jasmine-client-unit` reports success quite quickly. The other tests are waiting for the mirror, presumably, and take forever.

2. Eventually, they are started up. `jasmine-server-integration` reports success.

3. Change `modules/TodoApp/server/__tests__/integration/Todo-test.js` so it fails, e.g. `expect(true).toEqual(false);`

4. Meteor rebuilds and restarts.

5. Test reports failure.

6. Change it back to `expect(true).toEqual(true);`

7. Meteor rebuilds and restarts.

8. **Test *still* reports failure.**

9. Modify test in a trivial way (add some whitespace), save.

10. Meteor rebuilds and restarts.

11. Test now reports success.

**Comment by eXon** [comment]
I'm aware of that problem. They take forever to run because it needs to download npm modules again. I can probably find a way to reuse those from the main server.

For the test still failing, i also have a hard time with it. It seems like you have to change twice your file. I haven't found a fix yet.

**Comment by optilude** [comment]
One possible piece of the puzzle: it looks like the velocity mirror isn't updated when the code is updated. 

For instance, I added some `console.log()` statements to my server-side code (a bit of server-side code under test), saved, Meteor restarted in the main console. Tailing the mirror logs, I see nothing. Then, I made a trivial change, saved, Meteor restarted again, and this time the logging appears.

Same type of behaviour for "Client restarted" when changing a client integration test script, takes two saves to "stick".

**Comment by optilude** [comment]
Another piece of the puzzle, at least for client integration tests:

The problem is (probably) definitely that only every other save actually gets picked up, rather than a race condition type thing where you end up with the previous version of a saved file being bundled.

The easiest way to test that is to put a statement like `console.log("Increment 1")` at the top of a test file. Save. Wait for the page to refresh. Nothing happens. Change it again to `"Increment 2"` and save. Console now prints `Increment 2`. Change it again to `"Increment 3"`. Console still prints `Increment 2`. Change it again to "`Increment 4`" and it prints `Increment 4`.

I thought perhaps the hot module reloader was at fault, but no amount of force reload of the browser makes a difference.

**Comment by optilude** [comment]
One more data point I just noticed:

When using a kickstart-like setup, in the Chrome inspector's "Source" tab, if I use Cmd+P to open a file, I have two versions of each file:

![image](https://cloud.githubusercontent.com/assets/160906/11764336/7574556a-a123-11e5-888f-99b9876d8eda.png)

The "local" file (with the computer icon) is "one save behind" the `webpack://` one, just like the test files are.

I could've swore I saw the "out of date" file referred to with a `meteor://` prefix, but I can't find that now when looking again.

**Comment by eXon** [comment]
This is weird. We badly need a fix for this. I'm still looking.

**Comment by vuongngo** [comment]
I have the same problem with client integration test. It seems there's problem with client/entry.js. I once change integration test from TRUE to FALSE, it still passed until I accidentally make change to client/entry.js, and the test become fail. Hopefully that provides a hint :). Anyways, thanks for this awesome project.

**Comment by eXon** [comment]
Tests are going to be rewritten so I'm closing this.
