### ISSUE TITLE
using sass-loader for production

### ISSUE THREAD

**Issue by dmitry-sher** [thereactivestack/kickstart-meteor-react#36]
Is it even possible? I managed to have it in local development mode, but production fails. I made a test project here: https://github.com/dmitry-sher/kickstart-sass-test

The error is as follows:

    ReferenceError: window is not defined

It happens after i add sass-loader. The error is coming from Helmet in latest builds, but in previous commits it did come from scss file. It's somehow connected to server builds, but the process is mystery to me...

Steps to reproduce:
 1. Clone
 2. run 
    meteor run --production

If you encounter an error like this on Mac:

    ERROR in The `libsass` binding was not found in %PROJECT_PATH%/.meteor/local/webpack-npm/node_modules/node-sass/vendor/darwin-x64-11/binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.

then the simplest way is to download binding file and place where it looks for it.. It's some node versions mingling.

**Comment by eXon** [comment]
This is because Meteor is running on Node 0.10.40 and your local Node version is different. This was fixed before but it came back :/. I'll find a solution to fix this since so many people are using SASS.

**Comment by dmitry-sher** [comment]
The 'missing binding' is not so big problem, there is workaround for it. The problem is with 'window is not defined' - sass + server production build is not working. 

Thanks a lot in advance, anyway )

**Comment by eXon** [comment]
Your problem is in `entry/server/webpack.config.js`:

```javascript
{ test: /\.scss$/, loader: 'style!css/locals!sass' },
```

You just need to remove style! at the beginning. This is causing the window undefined.

**Comment by dmitry-sher** [comment]
whoa! it works! thanx!

**Comment by dmitry-sher** [comment]
ok, now  

    meteor run --production

works, but there are still some exceptions for server bundle. I updated test repo and provided a build script. After first request to the app, there is an exception in logs:

    error while server-rendering ReferenceError: window is not defined
        at t.l.value (webpack:///Users/dmitrysher/Desktop/work/MERIT/src/kickstart-s
    ass-test/.meteor/local/webpack-npm/~/react/lib/ReactCompositeComponent.js:421:1)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWit
    houtOwnerOrContext (../../../../../Desktop/work/MERIT/src/kickstart-sass-test/re
    act/lib/ReactCompositeComponent:587:1)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (.
    ./../../../../Desktop/work/MERIT/src/kickstart-sass-test/react/lib/ReactComposit
    eComponent:607:1)
        at [object Object].ReactCompositeComponentMixin.mountComponent (../../../../
    ../Desktop/work/MERIT/src/kickstart-sass-test/react/lib/ReactCompositeComponent:
    220:1)

and so on. It happens only with server bundle. Application works, nevertheless. But this exception is disturbing. It happens on Mac OS X 10.10.5 with nvm and on Ubuntu 14.04 with plain old 0.10.40. I have more tests for today for Cordova also, but info on that gonna come later.

I provided a comprehensive build script to catch this error. You need to have running mongod on localhost for this example to run. Steps to reproduce:

1. Clone repo in some temporary folder. Folder structure:

    kickstart-test
        build
        kickstart-sass-test  <--- cloned repo

2. cd kickstart-sass-test and run build.sh. wait for app to start. logs would come in this terminal window.
3. open http://localhost:3030 in browser and check the logs.

**Comment by eXon** [comment]
`window is not defined` means you are trying to execute some code on the server that can only run on the client.

**Comment by eXon** [comment]
Pretty sure this is outdated issue
