### ISSUE TITLE
How to conditionally SSR load a css/less file?

### ISSUE THREAD

**Issue by D1no** [thereactivestack/kickstart-meteor-react#38]
I think I have tried everything. How can I conditionally SSR load a css/less file? On the client, `style/usable` works. But I don't know how to tell the server to include modules conditionally.

I can capture the on the main components constructor the url query. Ie: `localhost/?theme=ios`. A conditional require based on that does not seem to work.

How do you conditionally require a .less file?

**Comment by eXon** [comment]
Are you using the ExtractTextPlugin? If yes, I would set a custom loader on .ios.less and save it on a different file. Then, I will use javascript to detect if you are on iOS and add the CSS file if so.

SSR will be weird but my guess is your app don't need it. Or you can write a custom code that add the CSS on the HTML meteor send.

Let me know if you need more help to figure out how to do that.

**Comment by D1no** [comment]
We are building a lot of big corporate health and business intelligence apps where, out of security concerns (Europe) JavaScript can be initially heavily restricted, so loading styles just via client js is a bad idea.

On the client I am able to use [this "style/usable" loader](https://github.com/webpack/style-loader#reference-counted-api) config. But on the server it does not load. Should the SSR webpack config not simply ignore require statements that are outside of a condition? I am surprised it does not work for styles. Any hints of how you would do that? I feel I am missing some particular webpack specialities on the server...

**Btw**: How can we access the request header in RRSSR to act up-on the user agent? Or how could it be possible.

*Some Context*
Touch2S is a shared, public ios/material boilerplate. But the goal internally is to advance the stack to be capable to initial render with full style. Basically: Imagine some guy in some high level executive department gets shared an initial dashboard report (some state of a "Business Intelligence App") but does not have yet the JavaScript policy for the internal domain. He can still engage in the content thanks to SSR, without sacrificing much usability. Later by getting the policy clearance, he benefits of a full client side web app.

**Comment by eXon** [comment]
I understand the problem you're going through. I think it would be cool to support this with react-router-ssr. It guess it would need to collect the styles and them them, just like I was doing with style-collector-loader.

I'll try to take a look when I have a few minutes.

**Comment by D1no** [comment]
I think I found the reason for the problem. Basically webpack does not do any loader magic on the server. I had those syntax errors but thought it was mis-configuration.
http://stackoverflow.com/questions/33489192/how-to-import-css-file-on-isomorphic-react-webpack
When I have time, I'll try to get this in place.

**Comment by D1no** [comment]
Not sure if we should move this to the meteor-webpack repo, but does meteor-webpack currently handle the require statements on the server or is that plain old node-require handling?

Because in the later case, maybe (webpack-isomorphic-tools)[https://github.com/halt-hammerzeit/webpack-isomorphic-tools] could be generically included to enable the server to virtually behave completly similar on the meteor server as on the meteor client? Not sure if that also touches RRSSR

**Comment by eXon** [comment]
With the 1.0 release, the server code will do a real Node.js require.

**Comment by eXon** [comment]
Not sure if this is still relevant. Let me know if it is!
