### ISSUE TITLE
react-toolbox integration

### ISSUE THREAD

**Issue by aurelien-ctouch** [thereactivestack/kickstart-meteor-react#42]
Hi, thanks for your great work ! 
I am trying to integrate react-toolbox with your awesome work, but I am stuck. I have forked your repo to help anybody to reproduce the issue, with two tags (first/second try):
At first I have enabled scss, added needed webpack loaders as advised by react-toolbox guidelines and included a simple empty button without styling.
With this [first attempt](https://github.com/aurelien-ctouch/kickstart-simple/tree/first_try) I get the following error at page loading :
> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)

It is a common issue due to several versions of React loaded. I have checked npm ls, and I got one single React dependency. I assumed that the "node React" was conflicting with the "meteor React", so I tried to add React as external,
With this [second attempt](https://github.com/aurelien-ctouch/kickstart-simple/tree/second_try) the previous error disappeared, but on button click/over, I keep getting another error:
> React can't find the root component node for data-reactid value .0.1.1. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time. externals: { // Add global variables you would like to import 'react': 'React' }

It seems that 2 instances of React are loaded, even though this time it is the same version. I even tried to remove react-runtime from Meteor, without success.

At this point I am stuck, the one thing I don't understand is why npm ls gives me a React **direct** dependency, although it is missing in the webpack.packages.json.

Thanks a lot for your time and effort !

**Comment by eXon** [comment]
This shouldn't be a problem now that we use React from NPM
