### ISSUE TITLE
File Paths to Images from SCSS?

### ISSUE THREAD

**Issue by nicholasalanbrown** [thereactivestack/kickstart-meteor-react#49]
Amazing work. 

I see how to include images from components, but how can I reference them from ```.scss``` files? I can't seem to get them to render, and placing them in a ```/public``` folder doesn't seem to work either.

**Comment by eXon** [comment]
The easiest way is to set a relative path. Webpack will take care of bundling your asset with it.

Example:

```css
.trash {
  background: url(img/trash.png);
}
```

Then you let webpack do all the work for you :)

**Comment by nicholasalanbrown** [comment]
Er...I don't think I'm following. a "relative path" relative to what exactly? If I have a file:

```
ToDoApp/client/styles/styles.import.scss

.background {
  background: url('img/welcome.jpg');
}

```

I can't get the background to render no matter where I place the image. I've tried both ```.ToDoApp/client/styles/img/welcome.jpg``` and .```ToDoApp/client/img/welcome.jpg``` with no luck. Also, just to clarify, I'm pretty sure there should be quotation marks around the image URL, no?

**Comment by eXon** [comment]
Are you importing your SCSS file within your component?

Your relative path will be with your .scss file. You can also add an includePaths by using webpack.json like this:
```json
{
  "sass": {
    "includePaths": ["public/assets"]
  }
}
```

For the quotation marks they are optional in CSS.

**Comment by nicholasalanbrown** [comment]
Hmm, when trying as you suggest with the include paths, I'm not successful. I've been placing all of my ```.scss``` files in my include path folder since importing them in my component always gives me this error:

```
ERROR in The `libsass` binding was not found in /Users/nicholasalanbrown/Source/mealplan-react/node_modules/node-sass/vendor/darwin-x64-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

I've seen similar errors mentioned in threads related to this package but none of the suggested fixes have worked for me. I was not able to figure out to point my project to a previous Node version via ```nvm```

**Comment by eXon** [comment]
This happens because you have a different Node.js version than Meteor (0.10.40 ATM). This problem only happens with sass so you'll have to deal with it (there is no other way).

Use `nvm` to set your Node.js version to 0.10.40. That way you don't have to remove the last version on your computer.

**Comment by nicholasalanbrown** [comment]
Got it, I was not able to figure out how to do that exactly. I appreciate
your help.
