### ISSUE TITLE
How to make webpack find Meteor exports?

### ISSUE THREAD

**Issue by alesn** [thereactivestack/kickstart-meteor-react#50]
Hi,
I'm using latest webpack:webpack with Meteor 1.3. Trying to import Meteor exports like:
import { Meteor } from 'meteor/meteor';
doesn't work. It throws an error: Module not found: Error: Cannot resolve module 'meteor/meteor'

Does webpack:webpack need any configuration so it can find the module or how can make importing Meteor exports to work?

**Comment by eXon** [comment]
Webpack is reading all exports from Meteor and import { Meteor } from 'meteor/meteor'; should work!
